export const messageData=[
  {
    "id": "377",
    "name": null,
    "createTime": "2023-02-16 15:25:14",
    "updateTime": "2023-02-16 15:25:14",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": null,
    "contentText": null,
    "contentType": "file",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 15:25:14",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [
      {
        "uid": null,
        "name": "打车费.pdf",
        "realName": "20230216152514.pdf",
        "content": null,
        "path": "/project/tenant/platform/config/cmc/chat/20230216152514/20230216152514.pdf",
        "url": "http://100.66.2.110:5080/rss/project/tenant/platform/config/cmc/chat/20230216152514/20230216152514.pdf",
        "size": "99.578KB"
      }
    ],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T07:25:14.443Z\""
  },
  {
    "id": "378",
    "name": null,
    "createTime": "2023-02-16 15:25:28",
    "updateTime": "2023-02-16 15:25:28",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "fdsf",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 15:25:28",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T07:25:28.223Z\""
  },
  {
    "id": "379",
    "name": null,
    "createTime": "2023-02-16 15:25:30",
    "updateTime": "2023-02-16 15:25:30",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "fdsff",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 15:25:30",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T07:25:30.033Z\""
  },
  {
    "id": "380",
    "name": null,
    "createTime": "2023-02-16 15:25:32",
    "updateTime": "2023-02-16 15:25:32",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "fdsaf",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 15:25:32",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T07:25:31.834Z\""
  },
  {
    "id": "423",
    "name": null,
    "createTime": "2023-02-16 17:36:06",
    "updateTime": "2023-02-16 17:36:06",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "11",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 17:36:06",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T09:36:05.839Z\""
  },
  {
    "id": "424",
    "name": null,
    "createTime": "2023-02-16 17:36:18",
    "updateTime": "2023-02-16 17:36:18",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "666",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 17:36:18",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T09:36:17.862Z\""
  },
  {
    "id": "426",
    "name": null,
    "createTime": "2023-02-16 17:37:56",
    "updateTime": "2023-02-16 17:37:56",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "q",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 17:37:56",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T09:37:56.488Z\""
  },
  {
    "id": "427",
    "name": null,
    "createTime": "2023-02-16 17:38:05",
    "updateTime": "2023-02-16 17:38:05",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "252",
      "orgId": null,
      "name": "jietest4",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "1",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-16 17:38:05",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-16T09:38:04.903Z\""
  },
  {
    "id": "494",
    "name": null,
    "createTime": "2023-02-17 14:40:08",
    "updateTime": "2023-02-17 14:40:08",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "2",
      "orgId": null,
      "name": "平台管理员",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": "dfdfdsf",
    "contentText": null,
    "contentType": "text",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-17 14:40:08",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-17T06:40:06.513Z\""
  },
  {
    "id": "495",
    "name": null,
    "createTime": "2023-02-17 14:40:33",
    "updateTime": "2023-02-17 14:40:33",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "2",
      "orgId": null,
      "name": "平台管理员",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": null,
    "contentText": null,
    "contentType": "image",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-17 14:40:33",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [
      {
        "uid": null,
        "name": "1638177726(1).jpg",
        "realName": "20230217144033.jpg",
        "content": null,
        "path": "/project/tenant/platform/config/cmc/chat/20230217144033/20230217144033.jpg",
        "url": "http://100.66.2.110:5080/rss/project/tenant/platform/config/cmc/chat/20230217144033/20230217144033.jpg",
        "size": "0.497M"
      }
    ],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-17T06:40:31.635Z\""
  },
  {
    "id": "496",
    "name": null,
    "createTime": "2023-02-17 14:40:53",
    "updateTime": "2023-02-17 14:40:53",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "2",
      "orgId": null,
      "name": "平台管理员",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": null,
    "contentText": null,
    "contentType": "image",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-17 14:40:53",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [
      {
        "uid": null,
        "name": "banner1@1x.jpg",
        "realName": "20230217144053.jpg",
        "content": null,
        "path": "/project/tenant/platform/config/cmc/chat/20230217144053/20230217144053.jpg",
        "url": "http://100.66.2.110:5080/rss/project/tenant/platform/config/cmc/chat/20230217144053/20230217144053.jpg",
        "size": "0.117M"
      }
    ],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-17T06:40:51.532Z\""
  },
  {
    "id": "497",
    "name": null,
    "createTime": "2023-02-17 14:43:29",
    "updateTime": "2023-02-17 14:43:29",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "2",
      "orgId": null,
      "name": "平台管理员",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": null,
    "contentText": null,
    "contentType": "image",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-17 14:43:29",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [
      {
        "uid": null,
        "name": "OIP-C (1).jpg",
        "realName": "20230217144329.jpg",
        "content": null,
        "path": "/project/tenant/platform/config/cmc/chat/20230217144329/20230217144329.jpg",
        "url": "http://100.66.2.110:5080/rss/project/tenant/platform/config/cmc/chat/20230217144329/20230217144329.jpg",
        "size": "15.301KB"
      }
    ],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-17T06:43:27.759Z\""
  },
  {
    "id": "498",
    "name": null,
    "createTime": "2023-02-17 14:43:34",
    "updateTime": "2023-02-17 14:43:34",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "2",
      "orgId": null,
      "name": "平台管理员",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": null,
    "contentText": null,
    "contentType": "file",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-17 14:43:34",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [
      {
        "uid": null,
        "name": "Fwp考试.doc",
        "realName": "20230217144334.doc",
        "content": null,
        "path": "/project/tenant/platform/config/cmc/chat/20230217144334/20230217144334.doc",
        "url": "http://100.66.2.110:5080/rss/project/tenant/platform/config/cmc/chat/20230217144334/20230217144334.doc",
        "size": "1.228M"
      }
    ],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-17T06:43:33.093Z\""
  },
  {
    "id": "499",
    "name": null,
    "createTime": "2023-02-17 14:43:56",
    "updateTime": "2023-02-17 14:43:56",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "2",
      "orgId": null,
      "name": "平台管理员",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": null,
    "contentText": null,
    "contentType": "file",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-17 14:43:56",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [
      {
        "uid": null,
        "name": "Fwp考试.doc",
        "realName": "20230217144356.doc",
        "content": null,
        "path": "/project/tenant/platform/config/cmc/chat/20230217144356/20230217144356.doc",
        "url": "http://100.66.2.110:5080/rss/project/tenant/platform/config/cmc/chat/20230217144356/20230217144356.doc",
        "size": "1.228M"
      }
    ],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-17T06:43:55.226Z\""
  },
  {
    "id": "500",
    "name": null,
    "createTime": "2023-02-17 14:44:12",
    "updateTime": "2023-02-17 14:44:12",
    "delete": null,
    "deleteTime": null,
    "type": "CHAT",
    "from": {
      "id": "2",
      "orgId": null,
      "name": "平台管理员",
      "phone": null,
      "email": null,
      "openId": null,
      "leaf": null
    },
    "to": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "realReceivers": [
      {
        "id": "252",
        "orgId": null,
        "name": "jietest4",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": true
      }
    ],
    "title": null,
    "content": null,
    "contentText": null,
    "contentType": "file",
    "contentFiles": [],
    "status": "20",
    "urlType": null,
    "url": null,
    "source": null,
    "sendTime": "2023-02-17 14:44:12",
    "receiveTime": null,
    "viewTime": null,
    "replyTime": null,
    "isPush": "0",
    "isIllegal": null,
    "channel": null,
    "ruleId": null,
    "totalCount": "1",
    "successCount": "1",
    "failCount": "0",
    "nullCount": "0",
    "blacklistCount": "0",
    "messageType": null,
    "accessory": [
      {
        "uid": null,
        "name": "Fwp考试.doc",
        "realName": "20230217144412.doc",
        "content": null,
        "path": "/project/tenant/platform/config/cmc/chat/20230217144412/20230217144412.doc",
        "url": "http://100.66.2.110:5080/rss/project/tenant/platform/config/cmc/chat/20230217144412/20230217144412.doc",
        "size": "1.228M"
      }
    ],
    "singleChannel": null,
    "delayLevel": null,
    "timeStamp": "\"2023-02-17T06:44:10.317Z\""
  }
]
export const newMessage=[
    {
      "id": "501",
      "name": null,
      "createTime": "2023-02-17 14:49:46",
      "updateTime": "2023-02-17 14:49:46",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "tyrtyrty",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:46",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:45.201Z\""
    },
    {
      "id": "502",
      "name": null,
      "createTime": "2023-02-17 14:49:49",
      "updateTime": "2023-02-17 14:49:49",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "4140",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:49",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:47.497Z\""
    },
    {
      "id": "503",
      "name": null,
      "createTime": "2023-02-17 14:49:50",
      "updateTime": "2023-02-17 14:49:50",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "44244",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:50",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:48.824Z\""
    },
    {
      "id": "504",
      "name": null,
      "createTime": "2023-02-17 14:49:51",
      "updateTime": "2023-02-17 14:49:51",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:51",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:49.848Z\""
    },
    {
      "id": "505",
      "name": null,
      "createTime": "2023-02-17 14:49:52",
      "updateTime": "2023-02-17 14:49:52",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "55",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:52",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:50.833Z\""
    },
    {
      "id": "506",
      "name": null,
      "createTime": "2023-02-17 14:49:52",
      "updateTime": "2023-02-17 14:49:52",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:52",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:51.072Z\""
    },
    {
      "id": "507",
      "name": null,
      "createTime": "2023-02-17 14:49:52",
      "updateTime": "2023-02-17 14:49:52",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:52",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:51.377Z\""
    },
    {
      "id": "508",
      "name": null,
      "createTime": "2023-02-17 14:49:53",
      "updateTime": "2023-02-17 14:49:53",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:53",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:51.665Z\""
    },
    {
      "id": "509",
      "name": null,
      "createTime": "2023-02-17 14:49:53",
      "updateTime": "2023-02-17 14:49:53",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5\n",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:53",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:51.993Z\""
    },
    {
      "id": "510",
      "name": null,
      "createTime": "2023-02-17 14:49:55",
      "updateTime": "2023-02-17 14:49:55",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5\n",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:55",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:53.785Z\""
    },
    {
      "id": "511",
      "name": null,
      "createTime": "2023-02-17 14:49:55",
      "updateTime": "2023-02-17 14:49:55",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5\n",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:55",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:54.344Z\""
    },
    {
      "id": "512",
      "name": null,
      "createTime": "2023-02-17 14:49:56",
      "updateTime": "2023-02-17 14:49:56",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5\n",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:56",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:54.945Z\""
    },
    {
      "id": "513",
      "name": null,
      "createTime": "2023-02-17 14:49:57",
      "updateTime": "2023-02-17 14:49:57",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:57",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:55.825Z\""
    },
    {
      "id": "514",
      "name": null,
      "createTime": "2023-02-17 14:49:57",
      "updateTime": "2023-02-17 14:49:57",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:57",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:56.178Z\""
    },
    {
      "id": "515",
      "name": null,
      "createTime": "2023-02-17 14:49:58",
      "updateTime": "2023-02-17 14:49:58",
      "delete": null,
      "deleteTime": null,
      "type": "CHAT",
      "from": {
        "id": "2",
        "orgId": null,
        "name": "平台管理员",
        "phone": null,
        "email": null,
        "openId": null,
        "leaf": null
      },
      "to": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "realReceivers": [
        {
          "id": "157",
          "orgId": null,
          "name": "test2222",
          "phone": null,
          "email": null,
          "openId": null,
          "leaf": true
        }
      ],
      "title": null,
      "content": "5",
      "contentText": null,
      "contentType": "text",
      "contentFiles": [],
      "status": "20",
      "urlType": null,
      "url": null,
      "source": null,
      "sendTime": "2023-02-17 14:49:58",
      "receiveTime": null,
      "viewTime": null,
      "replyTime": null,
      "isPush": "0",
      "isIllegal": null,
      "channel": null,
      "ruleId": null,
      "totalCount": "1",
      "successCount": "1",
      "failCount": "0",
      "nullCount": "0",
      "blacklistCount": "0",
      "messageType": null,
      "accessory": [],
      "singleChannel": null,
      "delayLevel": null,
      "timeStamp": "\"2023-02-17T06:49:56.481Z\""
    }
  ]